name: Build project website and deploy to gh-pages

on:
  push:
    branches:
    - gh-pages-source
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: gh-pages-source
    - uses: jayanthkoushik/paje@master
      with:
        setupscript: |
          cp index.md /www/
          cp -r css /www/
          cp -r js /www/
          cp -r imgs /www/
          cp _includes/* /www/_includes/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

