name: Build project website and deploy to gh-pages

on:
  workflow_dispatch:
  push:
    branches:
    - gh-pages-source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jayanthkoushik/paje@v6.2.1
      with:
        setupscript: |
          cp index.md /www/
          cp -r imgs /www/
          cp _includes/* /www/_includes/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
